apiVersion: v1
kind: Pod
metadata:
  name: scheduler
  namespace: default
spec:
  containers:
  - name: busybox
    image: jzp1025/mxnet:gpu_sleep
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Always
